package com.modar.ai;

import android.app.Activity;import android.os.Bundle;import android.graphics.Color;import android.graphics.drawable.GradientDrawable;import android.view.Gravity;import android.view.View;import android.widget.*;import android.content.Intent;

/** Первый экран: отдельная регистрация и вход клиента/водителя. */
public class AuthActivity extends Activity{
 private LinearLayout root,card; private EditText name,phone,email,password,code; private TextView title,subtitle,roleLabel; private boolean register=true;
 private int dp(int n){return (int)(n*getResources().getDisplayMetrics().density+.5f);} private GradientDrawable bg(int color,int radius){GradientDrawable g=new GradientDrawable();g.setColor(color);g.setCornerRadius(dp(radius));return g;}
 @Override public void onCreate(Bundle b){super.onCreate(b);if(!getSharedPreferences("cargo_auth",MODE_PRIVATE).getString("token","").isEmpty()){openApp();return;}showForm();}
 private TextView tv(String text,int size,int color){TextView v=new TextView(this);v.setText(text);v.setTextSize(size);v.setTextColor(color);return v;}
 private EditText input(String hint){EditText e=new EditText(this);e.setHint(hint);e.setSingleLine(true);e.setTextSize(16);e.setPadding(dp(16),0,dp(16),0);e.setTextColor(Color.DKGRAY);e.setHintTextColor(Color.rgb(145,145,145));e.setBackground(bg(Color.rgb(247,247,247),14));LinearLayout.LayoutParams p=new LinearLayout.LayoutParams(-1,dp(56));p.setMargins(0,dp(6),0,dp(6));e.setLayoutParams(p);return e;}
 private TextView button(String text,boolean filled){TextView v=tv(text,16,filled?Color.WHITE:Color.rgb(40,40,40));v.setGravity(Gravity.CENTER);v.setTypeface(null,android.graphics.Typeface.BOLD);v.setBackground(bg(filled?Color.rgb(242,139,82):Color.WHITE,14));v.setPadding(8,0,8,0);v.setLayoutParams(new LinearLayout.LayoutParams(-1,dp(56)));return v;}
 private void base(){root=new LinearLayout(this);root.setOrientation(LinearLayout.VERTICAL);root.setGravity(Gravity.CENTER_HORIZONTAL);root.setPadding(dp(20),dp(30),dp(20),dp(20));root.setBackgroundColor(Color.rgb(16,19,24));ScrollView scroll=new ScrollView(this);scroll.addView(root);setContentView(scroll);TextView brand=tv("🚚  Грузовичок",22,Color.WHITE);brand.setGravity(Gravity.CENTER);root.addView(brand,new LinearLayout.LayoutParams(-1,dp(70)));card=new LinearLayout(this);card.setOrientation(LinearLayout.VERTICAL);card.setPadding(dp(28),dp(24),dp(28),dp(24));card.setBackground(bg(Color.WHITE,24));root.addView(card,new LinearLayout.LayoutParams(-1,-2));}
 private void showForm(){register=true;base();title=tv("Регистрация аккаунта",24,Color.rgb(45,45,45));title.setGravity(Gravity.CENTER);card.addView(title);subtitle=tv("Создайте аккаунт клиента или водителя",14,Color.GRAY);subtitle.setGravity(Gravity.CENTER);card.addView(subtitle);roleLabel=tv("Кто вы?",14,Color.GRAY);roleLabel.setPadding(0,dp(12),0,0);card.addView(roleLabel);Spinner role=new Spinner(this);role.setAdapter(new ArrayAdapter<String>(this,android.R.layout.simple_spinner_dropdown_item,new String[]{"Водитель", "Клиент"}));card.addView(role,new LinearLayout.LayoutParams(-1,dp(50)));name=input("ФИО");phone=input("Мобильный телефон");email=input("Электронная почта");password=input("Пароль");password.setInputType(0x81);card.addView(name);card.addView(phone);card.addView(email);card.addView(password);TextView submit=button("Зарегистрироваться",true);card.addView(submit);TextView have=tv("\nАккаунт уже есть?  Войти",15,Color.GRAY);have.setGravity(Gravity.CENTER);card.addView(have);submit.setOnClickListener(v->{if(name.getText().length()<3||phone.getText().length()<6||email.getText().length()<5||password.getText().length()<6){Toast.makeText(this,"Заполните все поля",Toast.LENGTH_SHORT).show();return;}showCode(role.getSelectedItemPosition()==0?"driver":"customer");});have.setOnClickListener(v->showLogin());root.addView(tv("\nНажимая кнопку, вы принимаете Пользовательское соглашение и Политику обработки персональных данных.",13,Color.LTGRAY));}
 private void showLogin(){register=false;base();title=tv("Вход в аккаунт",24,Color.rgb(45,45,45));title.setGravity(Gravity.CENTER);card.addView(title);card.addView(tv("Войдите по телефону или электронной почте",14,Color.GRAY));phone=input("Мобильный телефон или email");code=input("Код подтверждения");card.addView(phone);card.addView(code);TextView submit=button("Войти",true);card.addView(submit);TextView back=tv("\nНет аккаунта?  Зарегистрироваться",15,Color.GRAY);back.setGravity(Gravity.CENTER);card.addView(back);submit.setOnClickListener(v->{if(phone.getText().length()<5||!"123456".equals(code.getText().toString())){Toast.makeText(this,"Введите код 123456 для тестового входа",Toast.LENGTH_LONG).show();return;}saveAndOpen("customer");});back.setOnClickListener(v->showForm());}
 private void showCode(String role){base();title=tv("Подтверждение контакта",24,Color.rgb(45,45,45));title.setGravity(Gravity.CENTER);card.addView(title);card.addView(tv("Введите код из SMS или письма\nТестовый код: 123456",14,Color.GRAY));code=input("Код подтверждения");card.addView(code);TextView submit=button("Подтвердить",true);card.addView(submit);submit.setOnClickListener(v->{if("123456".equals(code.getText().toString()))saveAndOpen(role);else Toast.makeText(this,"Неверный код",Toast.LENGTH_SHORT).show();});}
 private void saveAndOpen(String role){getSharedPreferences("cargo_auth",MODE_PRIVATE).edit().putString("token","local-"+System.currentTimeMillis()).putString("role",role).apply();openApp();}
 private void openApp(){startActivity(new Intent(this,MainActivity.class));finish();}
}
