package com.modar.ai;
import android.app.Activity;import android.content.Intent;import android.content.pm.PackageManager;import android.location.Location;import android.location.LocationManager;import android.net.Uri;import android.os.Bundle;import android.webkit.WebChromeClient;import android.webkit.WebSettings;import android.webkit.WebView;import android.webkit.WebViewClient;
public class MapActivity extends Activity{
 private static final int LOCATION=71; private double lat=55.75,lon=37.62;
 @Override public void onCreate(Bundle b){super.onCreate(b);setContentView(R.layout.activity_map);findViewById(R.id.map_back).setOnClickListener(v->finish());findViewById(R.id.map_2gis).setOnClickListener(v->open2gis()); WebView w=findViewById(R.id.map_web);WebSettings s=w.getSettings();s.setJavaScriptEnabled(true);s.setDomStorageEnabled(true);w.setWebViewClient(new WebViewClient());w.setWebChromeClient(new WebChromeClient());w.loadDataWithBaseURL("https://2gis.ru/",html(),"text/html","UTF-8",null);requestLocation();}
 private void requestLocation(){if(android.os.Build.VERSION.SDK_INT>=23&&checkSelfPermission(android.Manifest.permission.ACCESS_FINE_LOCATION)!=PackageManager.PERMISSION_GRANTED){requestPermissions(new String[]{android.Manifest.permission.ACCESS_FINE_LOCATION,android.Manifest.permission.ACCESS_COARSE_LOCATION},LOCATION);return;}try{LocationManager lm=(LocationManager)getSystemService(LOCATION_SERVICE);Location x=lm.getLastKnownLocation(LocationManager.GPS_PROVIDER);if(x==null)x=lm.getLastKnownLocation(LocationManager.NETWORK_PROVIDER);if(x!=null){lat=x.getLatitude();lon=x.getLongitude();}}catch(Exception ignored){}}
 private void open2gis(){try{startActivity(new Intent(Intent.ACTION_VIEW, Uri.parse("https://2gis.ru/geo/"+lon+","+lat)));}catch(Exception ignored){}}
 private String html(){return "<!doctype html><html><head><meta name='viewport' content='width=device-width,initial-scale=1'><script src='https://maps.api.2gis.ru/2.0/loader.js'></script><style>html,body,#map{height:100%;margin:0}</style></head><body><div id='map'></div><script>DG.then(function(){var map=DG.map('map',{center:[55.75,37.62],zoom:10,key:'fd9cfcd2-a76f-401a-9cee-a9f70c3bf40a'});DG.marker([55.891,37.445]).addTo(map).bindPopup('Химки → Мытищи · 1 800 ₽');DG.marker([55.742,37.615]).addTo(map).bindPopup('Центр → Подольск · 3 500 ₽');DG.marker([55.79,37.94]).addTo(map).bindPopup('Балашиха → Москва · 950 ₽');});</script></body></html>";}
}
