package com.modar.ai;
import android.app.Activity;import android.content.Intent;import android.content.pm.PackageManager;import android.location.Location;import android.location.LocationManager;import android.net.Uri;import android.os.Bundle;import android.webkit.WebChromeClient;import android.webkit.WebSettings;import android.webkit.WebView;import android.webkit.WebViewClient;
public class MapActivity extends Activity{
 private static final int LOCATION=71; private double lat=55.75,lon=37.62;
 @Override public void onCreate(Bundle b){super.onCreate(b);setContentView(R.layout.activity_map);findViewById(R.id.map_back).setOnClickListener(v->finish());findViewById(R.id.map_2gis).setOnClickListener(v->open2gis()); WebView w=findViewById(R.id.map_web);WebSettings s=w.getSettings();s.setJavaScriptEnabled(true);s.setDomStorageEnabled(true);w.setWebViewClient(new WebViewClient());w.setWebChromeClient(new WebChromeClient());w.loadDataWithBaseURL("https://2gis.ru/",html(),"text/html","UTF-8",null);requestLocation();}
 private void requestLocation(){if(android.os.Build.VERSION.SDK_INT>=23&&checkSelfPermission(android.Manifest.permission.ACCESS_FINE_LOCATION)!=PackageManager.PERMISSION_GRANTED){requestPermissions(new String[]{android.Manifest.permission.ACCESS_FINE_LOCATION,android.Manifest.permission.ACCESS_COARSE_LOCATION},LOCATION);return;}try{LocationManager lm=(LocationManager)getSystemService(LOCATION_SERVICE);Location x=lm.getLastKnownLocation(LocationManager.GPS_PROVIDER);if(x==null)x=lm.getLastKnownLocation(LocationManager.NETWORK_PROVIDER);if(x!=null){lat=x.getLatitude();lon=x.getLongitude();}}catch(Exception ignored){}}
 private void open2gis(){try{startActivity(new Intent(Intent.ACTION_VIEW, Uri.parse("https://2gis.ru/geo/"+lon+","+lat)));}catch(Exception ignored){}}
 private String html(){return "<!doctype html><html><head><meta name='viewport' content='width=device-width,initial-scale=1'><style>body{font-family:Arial;background:#101318;color:#f5f2ee;padding:24px}button{background:#f28b52;color:white;border:0;border-radius:12px;padding:15px;width:100%;font-size:16px}h2{margin-top:20px}</style></head><body><h2>Карта и заказы</h2><p>Для точной карты откройте 2ГИС. Приложение запросит ваше местоположение.</p><button onclick=\"location.href='https://2gis.ru'\">Открыть карту 2ГИС</button><h2>Ближайшие заявки</h2><p>Химки → Мытищи · 1 800 ₽</p><p>Центр → Подольск · 3 500 ₽</p></body></html>";}
}
